#include <kernel/idt.h>
#include <kernel/pic.h>
#include <kernel/panic.h>
#include <drivers/vga.h>
#include <lib/string.h>
static idt_entry_t idt[IDT_ENTRIES]; static idt_ptr_t idt_ptr; static isr_handler_t handlers[IDT_ENTRIES];
extern void isr0(void);extern void isr1(void);extern void isr2(void);extern void isr3(void);extern void isr4(void);extern void isr5(void);extern void isr6(void);extern void isr7(void);extern void isr8(void);extern void isr9(void);extern void isr10(void);extern void isr11(void);extern void isr12(void);extern void isr13(void);extern void isr14(void);extern void isr15(void);extern void isr16(void);extern void isr17(void);extern void isr18(void);extern void isr19(void);extern void isr20(void);extern void isr21(void);extern void isr22(void);extern void isr23(void);extern void isr24(void);extern void isr25(void);extern void isr26(void);extern void isr27(void);extern void isr28(void);extern void isr29(void);extern void isr30(void);extern void isr31(void);extern void isr32(void);extern void isr33(void);extern void isr34(void);extern void isr35(void);extern void isr36(void);extern void isr37(void);extern void isr38(void);extern void isr39(void);extern void isr40(void);extern void isr41(void);extern void isr42(void);extern void isr43(void);extern void isr44(void);extern void isr45(void);extern void isr46(void);extern void isr47(void);extern void isr128(void);
static void idt_set_gate(uint8_t n,uint32_t base,uint16_t sel,uint8_t flags){idt[n].base_low=base&0xFFFF;idt[n].base_high=(base>>16)&0xFFFF;idt[n].selector=sel;idt[n].zero=0;idt[n].flags=flags;}
void idt_init(void){memset(idt,0,sizeof(idt));memset(handlers,0,sizeof(handlers));idt_ptr.limit=sizeof(idt)-1;idt_ptr.base=(uint32_t)&idt;void(*isrs[])(void)={isr0,isr1,isr2,isr3,isr4,isr5,isr6,isr7,isr8,isr9,isr10,isr11,isr12,isr13,isr14,isr15,isr16,isr17,isr18,isr19,isr20,isr21,isr22,isr23,isr24,isr25,isr26,isr27,isr28,isr29,isr30,isr31,isr32,isr33,isr34,isr35,isr36,isr37,isr38,isr39,isr40,isr41,isr42,isr43,isr44,isr45,isr46,isr47};for(int i=0;i<48;i++)idt_set_gate(i,(uint32_t)isrs[i],0x08,0x8E);idt_set_gate(128,(uint32_t)isr128,0x08,0xEE) /* DPL=3: user mode can call INT 0x80 */;__asm__ volatile("lidt (%0)"::"r"(&idt_ptr));}
void idt_register_handler(uint8_t n,isr_handler_t h){handlers[n]=h;}
void isr_common_handler(registers_t*r){uint32_t n=r->int_no;if(n<IDT_ENTRIES&&handlers[n]){handlers[n](r);return;}if(n>=32&&n<=47){pic_send_eoi(n-32);return;}if(n<32){kpanic_exception(r);}}
